language: php

sudo: false

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER: weak

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 5.5
        - php: 5.6
        - php: 5.6
          env: SYMFONY_VERSION='2.8.*@dev' SYMFONY_DEPRECATIONS_HELPER: strict
        - php: 5.6
          env: SYMFONY_VERSION='3.0.*@dev' SYMFONY_DEPRECATIONS_HELPER: strict
        - php: 7.0
        - php: hhvm

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-source

script: phpunit
